spring:
  application:
    name: dubbo-auto-configuration-provider-demo
dubbo:
  scan:
    base-packages: com.newheart.service.impl
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://192.168.0.112:2181
#  registry:
#    address: N/A
