spring:
  application:
    name: dubbo-auto-configuration-provider-demo
dubbo:
  scan:
    base-packages: com.newheart.service.impl
#  protocol:
#      name: dubbo
#      port: 12345
#  多协议配置
  registry:
    address: zookeeper://192.168.0.112:2181
  protocols:
    dubbo:
      name: dubbo
      port: 12345
    http:
      name: http
      port: 8888
#  registry:
#    address: N/A
